# US - Baby Names

### Introduction:

We are going to use a subset of [US Baby Names](https://www.kaggle.com/kaggle/us-baby-names) from Kaggle.  
In the file it will be names from 2004 until 2014


### Step 1. Import the necessary libraries

In [1]:
import pandas as pd
import numpy as np

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/06_Stats/US_Baby_Names/US_Baby_Names_right.csv).

### Step 3. Assign it to a variable called baby_names.

In [2]:
baby_names = pd.read_csv('https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/06_Stats/US_Baby_Names/US_Baby_Names_right.csv')
baby_names.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1016395 entries, 0 to 1016394
Data columns (total 7 columns):
 #   Column      Non-Null Count    Dtype
---  ------      --------------    -----
 0   Unnamed: 0  1016395 non-null  int64
 1   Id          1016395 non-null  int64
 2   Name        1016395 non-null  object
 3   Year        1016395 non-null  int64
 4   Gender      1016395 non-null  object
 5   State       1016395 non-null  object
 6   Count       1016395 non-null  int64
dtypes: int64(4), object(3)
memory usage: 54.3+ MB

### Step 4. See the first 10 entries

In [3]:
baby_names.head(10)

   Unnamed: 0     Id      Name  Year Gender State  Count
0       11349  11350      Emma  2004      F    AK     62
1       11350  11351   Madison  2004      F    AK     48
2       11351  11352    Hannah  2004      F    AK     46
3       11352  11353     Grace  2004      F    AK     44
4       11353  11354     Emily  2004      F    AK     41
5       11354  11355   Abigail  2004      F    AK     37
6       11355  11356    Olivia  2004      F    AK     33
7       11356  11357  Isabella  2004      F    AK     30
8       11357  11358    Alyssa  2004      F    AK     29
9       11358  11359    Sophia  2004      F    AK     28

### Step 5. Delete the column 'Unnamed: 0' and 'Id'

In [4]:
baby_names.drop(['Unnamed: 0', 'Id'], axis=1, inplace=True)
baby_names.head()

      Name  Year Gender State  Count
0     Emma  2004      F    AK     62
1  Madison  2004      F    AK     48
2   Hannah  2004      F    AK     46
3    Grace  2004      F    AK     44
4    Emily  2004      F    AK     41

### Step 6. Are there more male or female names in the dataset?

In [6]:
baby_names.groupby('Gender').count()['Count']

Gender
F    558846
M    457549
Name: Count, dtype: int64

### Step 7. Group the dataset by name and assign to names

In [13]:
names = baby_names.groupby('Name').sum().sort_values('Count', ascending=False)
names = names.loc[:,'Count':]
names.head()

           Count
Name
Jacob     242874
Emma      214852
Michael   214405
Ethan     209277
Isabella  204798

### Step 8. How many different names exist in the dataset?

In [27]:
names.index.unique().value_counts().sum()

np.int64(17632)

### Step 9. What is the name with most occurrences?

In [28]:
names.sort_values('Count', ascending=False).head(1)

        Count
Name
Jacob  242874

### Step 10. How many different names have the least occurrences?

In [29]:
names[names['Count'] == names['Count'].min()].shape[0]

2578

### Step 11. What is the median name occurrence?

In [30]:
names.loc[names['Count'] == names['Count'].median()]

          Count
Name
Kaedence     49
Leylanie     49
Nabeel       49
Caleah       49
Nassir       49
...         ...
Kynsley      49
Fay          49
Maurilio     49
Mariann      49
Baily        49

[66 rows x 1 columns]

### Step 12. What is the standard deviation of names?

In [31]:
names.std()

Count    11006.069468
dtype: float64

### Step 13. Get a summary with the mean, min, max, std and quartiles.

In [32]:
names.describe()

               Count
count   17632.000000
mean     2008.932169
std     11006.069468
min         5.000000
25%        11.000000
50%        49.000000
75%       337.000000
max    242874.000000