# MPG Cars

Check out [Cars Exercises Video Tutorial](https://www.youtube.com/watch?v=avzLRBxoguU&list=PLgJhDSE2ZLxaY_DigHeiIDC1cD09rXgJv&index=3) to watch a data scientist go through the exercises

### Introduction:

The following exercise utilizes data from [UC Irvine Machine Learning Repository](https://archive.ics.uci.edu/ml/datasets/Auto+MPG)

### Step 1. Import the necessary libraries

In [1]:
import pandas as pd
import numpy as np

### Step 2. Import the first dataset [cars1](https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/05_Merge/Auto_MPG/cars1.csv) and [cars2](https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/05_Merge/Auto_MPG/cars2.csv).

   ### Step 3. Assign each to a to a variable called cars1 and cars2

In [6]:
cars1 = pd.read_csv('https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/05_Merge/Auto_MPG/cars1.csv')
cars2 = pd.read_csv('https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/05_Merge/Auto_MPG/cars2.csv')

### Step 4. Oops, it seems our first dataset has some unnamed blank columns, fix cars1

In [9]:
cars1.dropna(axis=1, inplace=True)
cars1.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model,origin,car
0,18.0,8,307,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302,140,3449,10.5,70,1,ford torino

### Step 5. What is the number of observations in each dataset?

In [11]:
print(cars1.shape,
cars2.shape, sep='\n')

(198, 9)
(200, 9)

### Step 6. Join cars1 and cars2 into a single DataFrame called cars

In [30]:
cars = pd.concat([cars1, cars2], axis=0)

In [25]:
cars2.tail()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model,origin,car
195,27.0,4,140,86,2790,15.6,82,1,ford mustang gl
196,44.0,4,97,52,2130,24.6,82,2,vw pickup
197,32.0,4,135,84,2295,11.6,82,1,dodge rampage
198,28.0,4,120,79,2625,18.6,82,1,ford ranger
199,31.0,4,119,82,2720,19.4,82,1,chevy s-10

In [32]:
cars.reset_index(drop=True, inplace=True)
cars.tail()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model,origin,car
393,27.0,4,140,86,2790,15.6,82,1,ford mustang gl
394,44.0,4,97,52,2130,24.6,82,2,vw pickup
395,32.0,4,135,84,2295,11.6,82,1,dodge rampage
396,28.0,4,120,79,2625,18.6,82,1,ford ranger
397,31.0,4,119,82,2720,19.4,82,1,chevy s-10

### Step 7. Oops, there is a column missing, called owners. Create a random number Series from 15,000 to 73,000.

In [33]:
owners = np.random.randint(15000, 73000, size=398)
owners

array([37808, 25909, 54946, 69245, 44140, 57923, 66877, 46213, 67518,
       48576, 15255, 54049, 29020, 57262, 55216, 31461, 61602, 46502,
       39739, 38169, 19292, 44900, 58421, 28873, 62316, 28816, 17141,
       16373, 22277, 55874, 66722, 50820, 55379, 65061, 40868, 40144,
       43120, 19199, 24069, 32144, 22172, 67321, 34644, 61416, 17580,
       23975, 18422, 30071, 45547, 46551, 50541, 31454, 58267, 30769,
       24196, 21114, 37216, 40629, 52298, 68122, 31349, 70689, 66226,
       38440, 41698, 60286, 34133, 36059, 62067, 44620, 17524, 71509,
       23080, 25846, 44621, 33274, 35584, 49340, 48271, 43183, 54483,
       18606, 22702, 53191, 29476, 19921, 16586, 46353, 20244, 22374,
       34079, 50497, 51551, 40346, 66723, 22611, 46048, 27054, 16528,
       63673, 38923, 56989, 71513, 44384, 52199, 35825, 43366, 32390,
       54448, 48180, 25056, 19477, 21143, 49430, 40669, 15534, 25653,
       54036, 44518, 59825, 32915, 67572, 37837, 28994, 69905, 18442,
       19432, 61109, 31715, 47667, 66801, 23371, 24891, 72100, 45481,
       31984, 62518, 61159, 56426, 61583, 51440, 30565, 31894, 63582,
       50612, 65001, 61668, 71174, 32714, 50213, 27100, 32162, 59508,
       49752, 54453, 25564, 68284, 40106, 43031, 66221, 70055, 63431,
       61138, 21440, 66027, 28869, 57937, 27287, 18259, 25956, 46642,
       34936, 56608, 71480, 37601, 49212, 46700, 25827, 29167, 67069,
       45428, 71595, 21401, 28259, 15782, 38520, 53971, 69074, 54111,
       52148, 41008, 15821, 15809, 28559, 66370, 70583, 23481, 54721,
       36446, 67102, 65717, 19424, 38056, 61897, 34822, 16565, 51464,
       69530, 45959, 68010, 27541, 46697, 70487, 42173, 37003, 32702,
       15750, 55129, 26856, 29031, 45683, 63593, 31033, 24339, 37330,
       36388, 25142, 48624, 62592, 38521, 25817, 17405, 62243, 15641,
       60713, 25046, 54223, 28169, 29618, 61600, 43575, 49616, 62568,
       52535, 31780, 55747, 28771, 32729, 21617, 39327, 35505, 54624,
       22845, 68252, 58056, 22147, 16171, 67859, 67967, 72804, 17951,
       28098, 67092, 38361, 26215, 35156, 31285, 63482, 32305, 26133,
       47934, 47859, 42300, 30749, 16486, 25956, 53310, 29624, 72224,
       26101, 62063, 50480, 35190, 57612, 38035, 68386, 18749, 47231,
       41561, 17791, 66466, 55833, 65360, 25258, 31964, 47139, 65893,
       45626, 67458, 70353, 52059, 27957, 46732, 50062, 54036, 64666,
       37039, 36179, 40037, 37387, 55305, 68614, 54230, 24100, 22998,
       59995, 44023, 54899, 51407, 18237, 41601, 66323, 19712, 61052,
       55306, 38178, 29202, 28703, 42752, 55076, 51257, 31224, 66264,
       49878, 35750, 57024, 21969, 28692, 58767, 54632, 45602, 71167,
       52566, 19785, 51451, 43345, 30799, 67686, 36839, 61058, 38946,
       67878, 64295, 30345, 23241, 45474, 39721, 29272, 29573, 66952,
       67065, 71168, 48920, 54412, 22178, 31691, 30423, 45515, 24723,
       37341, 70469, 57533, 20779, 65692, 34153, 51978, 52356, 36061,
       62600, 58572, 27375, 59715, 57218, 36266, 33817, 61890, 26569,
       54973, 67394, 27163, 53590, 27274, 27981, 38463, 62674, 44897,
       16246, 55858])

### Step 8. Add the column owners to cars

In [34]:
cars['owners'] = owners
cars.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model,origin,car,owners
0,18.0,8,307,130,3504,12.0,70,1,chevrolet chevelle malibu,37808
1,15.0,8,350,165,3693,11.5,70,1,buick skylark 320,25909
2,18.0,8,318,150,3436,11.0,70,1,plymouth satellite,54946
3,16.0,8,304,150,3433,12.0,70,1,amc rebel sst,69245
4,17.0,8,302,140,3449,10.5,70,1,ford torino,44140